[package]
name = "csheap"
version = "0.1.5"
edition = "2021"
license = "MIT"
description = "A heap implementation over a vector"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
